name: Update JSON

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Update JSON file
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
        node update-json.js
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add data.json
        git commit -m 'Update data.json'
        git push